# 21 Aug 2012: Added logflushsecs
# 1 May  2013: Added wooddropscharcoal
# 16 May 2013: Added noburn(mob|player)by
# 13 Jun 2013: Added charcoaldrop node
# 22 SEp 2013: added lava place nodes

nerf_fire:
  logstart:
    player: world
    lightning: world
    crystal: world
#    lava: 
#    fireball: 
#    explosion: 
  whitelist: false
  nospread: world
  nostartby:
    op: false
#    lightning:
#      - world
#    lava:
#      - world_the_end
#      - nether
#    player:
#      - world
#    explosion: world
#    fireball: world
#    crystal: world
  nodamageto:
#    block: world
#    player:
#      fromlava: world, nether
#      fromfire:
#        - world
#    nonplayer:
#      fromlava: nether, world_the_end, world
#      fromfire: world
  noburnmobby:
    op: false
#    player: 
#    mob: 
  noburnplayerby:
    op: false
#    player: 
#    mob: 
  logflushsecs: 600
  noplacelavaby: 
    op: false
#    player: world
  logplace:
    lava: world  
  wooddropscharcoal: world
# Following is global, applying to all worlds in wooddropscharcoal
  charcoaldrop:
    random: true
    max: 3
    # Set in order of Oak/Generic, Spruce/Redwood, Birch, Jungle
    #treetypemax: [2,3,0,1]

