# 21 Aug 2012: Added logflushsecs

nerf_fire:
  logstart:
    player: world
    lightning: world
    crystal: world
#    lava: 
#    fireball: 
#    explosion: 
  whitelist: false
  nospread: world
  nostartby:
    op: false
#    lightning:
#      - world
#    lava:
#      - world_the_end
#      - nether
#    player:
#      - world
#    explosion: world
#    fireball: world
#    crystal: world
  nodamageto:
#    block: world
#    player:
#      fromlava: world, nether
#      fromfire:
#        - world
#    nonplayer:
#      fromlava: nether, world_the_end, world
#      fromfire: world
  logflushsecs: 600
  wooddropscharcoal: false
