nerf_fire:
  logstart:
    player: world
    lightning: world
#   lava: 
  whitelist: false
  nospread: world
  nostartby:
    op: false
#    lightning:
#      - world
#    lava:
#      - world_the_end
#      - nether
#    player:
#      - world
#    explosion: world
  nodamageto:
#    block: world
#    player:
#      fromlava: world, nether
#      fromfire:
#        - world
#    nonplayer:
#      fromlava: nether, world_the_end, world
#      fromfire: world
