# May 8 2012: Added permissions node
# Aug 21 2012: Added af commands
# Nov 16 2012: Added extinguish command
# Nov 20 2012: Added antifire.fireman permission
# Nov 24 2012: Added reload, nostartby.fireball, logstart.fireball

name: AntiFire

main: com.yahoo.phil_work.antifire.AntiFire

version: 1.1

author: Filbert66

description: >

             Fire control, for starting/placement, damage, spread. Includes logging and commands to TP to last fire placement and to extinguish fires


commands:

  af:
    alias: antifire
    description: Admin AntiFire command prefix
    usage: <command> print|flush|save|reload|fireproof [\#]|burnable [\#]|spread [on|off]
    permission: antifire.admin
  log:
    alias: lf
    prefix: af
    description: Show fire starting log, reverse chrono order, optional player filter
    usage: <command> [next|<player>]
    permission: antifire.logview
    permission-message: You don't have permission to view fire logs
  tpf:  
    prefix: af
    description: Teleport to fire start location, last or # previous
    usage: <command> [last|#|<player>] 
    permission: antifire.teleport
    permission-message: You don't have permission to teleport to fire locations
  extinguish:
    description: Put out fires at location (optional radius) or world
    usage: <command> [#|world [all|<worldname>]] 
    permission: antifire.fireman
    permission-message: You don't have permission to extinguish fires
    
permissions:
  antifire.*:
    description: Gives access to ALL antifire features
    children:
      antifire.startfire: true
      antifire.logview: true
      antifire.teleport: true
      antifire.admin: true
      antifire.fireman: true
  antifire.startfire:
    description: Allows user to start a fire. Can be overridden by fireproof blocklist
  antifire.logview:
    description: Allows user to view fire start log in game.
    default: true
  antifire.teleport:
    description: Allows user to teleport to fire start locations
    default: op 
  antifire.fireman:
    description: Allows user to use 'extinguish' command on all worlds
    default: op
  antifire.admin:
    description: Allows user to query & set configs & flush logs
    default: op
